/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'irene' at '10/04/16 18:07' with Gradle 2.9
 *
 * @author irene, @date 10/04/16 18:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
